sudo: false

language: go

matrix:
  include:
    - go: 1.4
    - go: 1.5

install:
  - mkdir -p $HOME/gopath/src/k8s.io
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/contrib
  - go get github.com/tools/godep
  - go get github.com/golang/lint/golint
  - export PATH=$GOPATH/bin:$PATH
  - godep go install ./...

script:
  - hack/verify-all.sh
  - godep go test ./...

notifications:
  irc: "chat.freenode.net#kubernetes-dev"
